/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPrincipal;

import Controller.SistemaController;
import Model.Pessoa;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edivaldo
 */
public class PesquisaPessoa extends javax.swing.JDialog {

   private ArrayList<Pessoa> listaPessoa;
    private DefaultTableModel modelo;
    private Pessoa pessoa;
    public PesquisaPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModelo();
        pesquisar(0);
    }
    public PesquisaPessoa(int id) {
        pesquisar(id);
        pegaIdSelecionado(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisaAluno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisaAluno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPesquisaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaAlunoActionPerformed(evt);
            }
        });

        tblPesquisaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPesquisaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisaAluno);

        jLabel1.setText("Pesquisar");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaAlunoActionPerformed
        pesquisar(0);
    }//GEN-LAST:event_txtPesquisaAlunoActionPerformed

    private void tblPesquisaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaAlunoMouseClicked
        pegaIdSelecionado(0);
    }//GEN-LAST:event_tblPesquisaAlunoMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar(0);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisaPessoa dialog = new PesquisaPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesquisaAluno;
    private javax.swing.JTextField txtPesquisaAluno;
    // End of variables declaration//GEN-END:variables
 private void pesquisar(int id) {
        ArrayList<Pessoa> lista;
        if (id == 0) {
            lista = new SistemaController().getPessoaByNome(txtPesquisaAluno.getText());
            setModelo();
            for (Pessoa pessoa : lista) {
                insereTabela(pessoa);
            }
        } else {
            lista = new SistemaController().getPessoaByNome("");
        }
        listaPessoa = lista;
    }

    public void insereTabela(Pessoa pessoa) {
        Object[] linha = new Object[9];
        linha[0] = pessoa.getIdpessoa();
        linha[1] = pessoa.getNome();
        linha[2] = pessoa.getCpf();
        linha[3] = pessoa.getRg();
        linha[4] = pessoa.getSexo();
        linha[5] = pessoa.getDatanascimento();
        linha[6] = pessoa.getFone();
        linha[7] = pessoa.getEndereco();
        linha[8] = pessoa.getDatacadastro();

        modelo.addRow(linha);
    }

    private void setModelo() {
        modelo = new DefaultTableModel();
        modelo.addColumn("IDPESSOA");
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("SEXO");
        modelo.addColumn("DATANASCIMENTO");
        modelo.addColumn("FONE");
        modelo.addColumn("ENDERECO");
        modelo.addColumn("DATACADASTRO");
        tblPesquisaAluno.setModel(modelo);
    }

    private void pegaIdSelecionado(int id) {

        if (id == 0) {
            int linha = tblPesquisaAluno.getSelectedRow();
            id = Integer.parseInt(modelo.getValueAt(linha, 0).toString());
        }
        for (Pessoa pessoa : listaPessoa) {
            if (id == pessoa.getIdpessoa()) {
                this.pessoa = pessoa;
            }
        }
        this.dispose();
    }

    public Pessoa getPessoaSelecionado() {
        return pessoa;
    }
}
